In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv('CKD.csv')

In [3]:
dataset

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.000000,76.459948,c,3.0,0.0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.000000,76.459948,c,2.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.000000,76.459948,a,1.0,0.0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.000000,76.459948,d,1.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.000000,50.000000,c,0.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,219.000000,...,37.000000,9800.000000,4.400000,no,no,no,yes,poor,no,yes
395,51.492308,70.000000,c,0.0,2.0,normal,normal,notpresent,notpresent,220.000000,...,27.000000,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
396,51.492308,70.000000,c,3.0,0.0,normal,normal,notpresent,notpresent,110.000000,...,26.000000,9200.000000,3.400000,yes,yes,no,poor,poor,no,yes
397,51.492308,90.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,207.000000,...,38.868902,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
398,51.492308,80.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,100.000000,...,53.000000,8500.000000,4.900000,no,no,no,yes,poor,no,no

In [4]:
dataset=pd.get_dummies(dataset, dtype=int, drop_first=True)

In [5]:
dataset

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,0,0,0,0,0,0,1,1,0,1
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,0,0,0,0,0,1,0,0,1
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,0,0,0,0,0,1,0,0,1
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,0,0,0,0,0,1,0,1,1
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1,0,0,0,0,0,1,0,0,1
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1,0,0,1,1,0,1,0,1,1
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1,0,0,1,1,0,0,0,0,1
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1,0,0,1,1,0,1,0,1,1
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,1,0,0,0,0,0,1,0,0,0

In [6]:
dataset["classification_yes"].value_counts()

classification_yes
1    249
0    150
Name: count, dtype: int64

In [7]:
dataset.columns

Index(['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', 'classification_yes'],
      dtype='object')

In [8]:
independent= dataset [['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes']]

In [9]:
dependent=dataset [['classification_yes']]

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(independent, dependent, test_size = 1/3, random_state = 0)

In [11]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [12]:
dataset

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,0,0,0,0,0,0,1,1,0,1
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,0,0,0,0,0,1,0,0,1
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,0,0,0,0,0,1,0,0,1
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,0,0,0,0,0,1,0,1,1
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1,0,0,0,0,0,1,0,0,1
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1,0,0,1,1,0,1,0,1,1
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1,0,0,1,1,0,0,0,0,1
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1,0,0,1,1,0,1,0,1,1
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,1,0,0,0,0,0,1,0,0,0

In [13]:
from sklearn.neighbors import KNeighborsClassifier

In [14]:
from sklearn.model_selection import GridSearchCV
param_grid = {
    'n_neighbors': [3, 5, 7, 9, 11],
    'weights': ['uniform', 'distance'],
    'metric': ['euclidean', 'manhattan', 'minkowski']
}
grid = GridSearchCV(KNeighborsClassifier(), param_grid, refit = True, verbose = 3,n_jobs=-1,scoring='f1_weighted') 
grid.fit(X_train, y_train)

Fitting 5 folds for each of 30 candidates, totalling 150 fits

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:215: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)

GridSearchCV(estimator=KNeighborsClassifier(), n_jobs=-1,
             param_grid={'metric': ['euclidean', 'manhattan', 'minkowski'],
                         'n_neighbors': [3, 5, 7, 9, 11],
                         'weights': ['uniform', 'distance']},
             scoring='f1_weighted', verbose=3)

In [15]:
re=grid.cv_results_
grid_predictions = grid.predict(X_test) 
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, grid_predictions)
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, grid_predictions)

In [16]:
from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,grid_predictions,average='weighted')
print("The f1_macro value for best parameter {}:".format(grid.best_params_),f1_macro)

The f1_macro value for best parameter {'metric': 'manhattan', 'n_neighbors': 3, 'weights': 'uniform'}: 0.9701163285572423

In [17]:
print("The confusion Matrix:\n",cm)

The confusion Matrix:
 [[51  0]
 [ 4 78]]

In [18]:
print("The report:\n",clf_report)

The report:
               precision    recall  f1-score   support

           0       0.93      1.00      0.96        51
           1       1.00      0.95      0.97        82

    accuracy                           0.97       133
   macro avg       0.96      0.98      0.97       133
weighted avg       0.97      0.97      0.97       133

In [19]:
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test,grid.predict_proba(X_test)[:,1])

0.9873266379722621

In [20]:
table=pd.DataFrame.from_dict(re)

In [21]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_metric,param_n_neighbors,param_weights,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.053746,0.021550,1.224251,0.565275,euclidean,3,uniform,"{'metric': 'euclidean', 'n_neighbors': 3, 'wei...",0.981569,0.981233,0.944023,0.962573,1.000000,0.973880,0.019051,3
1,0.006250,0.007655,0.078121,0.000002,euclidean,3,distance,"{'metric': 'euclidean', 'n_neighbors': 3, 'wei...",0.981569,0.981233,0.944023,0.962573,1.000000,0.973880,0.019051,3
2,0.009379,0.007658,0.090615,0.006247,euclidean,5,uniform,"{'metric': 'euclidean', 'n_neighbors': 5, 'wei...",0.963284,0.962636,0.944023,0.962573,0.962573,0.959018,0.007502,11
3,0.016237,0.010874,0.080398,0.006526,euclidean,5,distance,"{'metric': 'euclidean', 'n_neighbors': 5, 'wei...",0.963284,0.981233,0.944023,0.962573,0.962573,0.962737,0.011770,9
4,0.012502,0.006251,0.090626,0.006250,euclidean,7,uniform,"{'metric': 'euclidean', 'n_neighbors': 7, 'wei...",0.908877,0.944161,0.925524,0.981217,0.962573,0.944470,0.025706,17
5,0.015628,0.000003,0.065626,0.006248,euclidean,7,distance,"{'metric': 'euclidean', 'n_neighbors': 7, 'wei...",0.908877,0.944161,0.925524,0.981217,0.962573,0.944470,0.025706,17
6,0.009374,0.007654,0.087498,0.007656,euclidean,9,uniform,"{'metric': 'euclidean', 'n_neighbors': 9, 'wei...",0.872586,0.925764,0.925524,0.981217,0.962573,0.933533,0.037299,25
7,0.015625,0.000001,0.072094,0.007522,euclidean,9,distance,"{'metric': 'euclidean', 'n_neighbors': 9, 'wei...",0.890759,0.925764,0.925524,0.981217,0.962573,0.937167,0.031639,21
8,0.012500,0.006250,0.084378,0.007657,euclidean,11,uniform,"{'metric': 'euclidean', 'n_neighbors': 11, 'we...",0.854321,0.925764,0.907035,0.981217,0.962573,0.926182,0.044461,29
9,0.003126,0.006252,0.075000,0.006250,euclidean,11,distance,"{'metric': 'euclidean', 'n_neighbors': 11, 'we...",0.872586,0.925764,0.925524,0.981217,0.962573,0.933533,0.037299,25
10,0.003125,0.006250,0.090627,0.006251,manhattan,3,uniform,"{'metric': 'manhattan', 'n_neighbors': 3, 'wei...",0.963284,0.981233,0.944023,0.981217,1.000000,0.973951,0.018941,1
11,0.009374,0.007654,0.075002,0.006249,manhattan,3,distance,"{'metric': 'manhattan', 'n_neighbors': 3, 'wei...",0.963284,0.981233,0.944023,0.981217,1.000000,0.973951,0.018941,1
12,0.009368,0.007649,0.084377,0.007655,manhattan,5,uniform,"{'metric': 'manhattan', 'n_neighbors': 5, 'wei...",0.926978,0.981233,0.944023,0.981217,0.981217,0.962934,0.023038,7
13,0.012500,0.006250,0.071875,0.007657,manhattan,5,distance,"{'metric': 'manhattan', 'n_neighbors': 5, 'wei...",0.926978,0.981233,0.944023,0.981217,0.981217,0.962934,0.023038,7
14,0.012501,0.006250,0.087498,0.007654,manhattan,7,uniform,"{'metric': 'manhattan', 'n_neighbors': 7, 'wei...",0.908877,0.944161,0.944023,0.981217,0.981217,0.951899,0.027173,13
15,0.010776,0.006340,0.075589,0.003310,manhattan,7,distance,"{'metric': 'manhattan', 'n_neighbors': 7, 'wei...",0.908877,0.944161,0.944023,0.981217,0.981217,0.951899,0.027173,13
16,0.003124,0.006249,0.090475,0.011758,manhattan,9,uniform,"{'metric': 'manhattan', 'n_neighbors': 9, 'wei...",0.908877,0.944161,0.925524,0.981217,0.981217,0.948199,0.029179,15
17,0.009376,0.007655,0.075001,0.006250,manhattan,9,distance,"{'metric': 'manhattan', 'n_neighbors': 9, 'wei...",0.908877,0.944161,0.925524,0.981217,0.981217,0.948199,0.029179,15
18,0.009374,0.007654,0.084375,0.007653,manhattan,11,uniform,"{'metric': 'manhattan', 'n_neighbors': 11, 'we...",0.908877,0.944161,0.907035,0.981217,0.944023,0.937063,0.027366,23
19,0.003124,0.006248,0.078124,0.009883,manhattan,11,distance,"{'metric': 'manhattan', 'n_neighbors': 11, 'we...",0.908877,0.944161,0.907035,0.981217,0.944023,0.937063,0.027366,23
20,0.009375,0.007654,0.088064,0.008115,minkowski,3,uniform,"{'metric': 'minkowski', 'n_neighbors': 3, 'wei...",0.981569,0.981233,0.944023,0.962573,1.000000,0.973880,0.019051,3
21,0.015861,0.010258,0.068694,0.007681,minkowski,3,distance,"{'metric': 'minkowski', 'n_neighbors': 3, 'wei...",0.981569,0.981233,0.944023,0.962573,1.000000,0.973880,0.019051,3
22,0.015626,0.000003,0.078124,0.000003,minkowski,5,uniform,"{'metric': 'minkowski', 'n_neighbors': 5, 'wei...",0.963284,0.962636,0.944023,0.962573,0.962573,0.959018,0.007502,11
23,0.003124,0.006249,0.079448,0.003198,minkowski,5,distance,"{'metric': 'minkowski', 'n_neighbors': 5, 'wei...",0.963284,0.981233,0.944023,0.962573,0.962573,0.962737,0.011770,9
24,0.010974,0.006231,0.085070,0.006558,minkowski,7,uniform,"{'metric': 'minkowski', 'n_neighbors': 7, 'wei...",0.908877,0.944161,0.925524,0.981217,0.962573,0.944470,0.025706,17
25,0.015615,0.000011,0.065631,0.006249,minkowski,7,distance,"{'metric': 'minkowski', 'n_neighbors': 7, 'wei...",0.908877,0.944161,0.925524,0.981217,0.962573,0.944470,0.025706,17
26,0.006251,0.007655,0.090624,0.006248,minkowski,9,uniform,"{'metric': 'minkowski', 'n_neighbors': 9, 'wei...",0.872586,0.925764,0.925524,0.981217,0.962573,0.933533,0.037299,25
27,0.015624,0.000006,0.071875,0.007654,minkowski,9,distance,"{'metric': 'minkowski', 'n_neighbors': 9, 'wei...",0.890759,0.925764,0.925524,0.981217,0.962573,0.937167,0.031639,21
28,0.009377,0.007657,0.084374,0.007657,minkowski,11,uniform,"{'metric': 'minkowski', 'n_neighbors': 11, 'we...",0.854321,0.925764,0.907035,0.981217,0.962573,0.926182,0.044461,29
29,0.012499,0.006250,0.065631,0.006246,minkowski,11,distance,"{'metric': 'minkowski', 'n_neighbors': 11, 'we...",0.872586,0.925764,0.925524,0.981217,0.962573,0.933533,0.037299,25

In [22]:
age_input=float(input("Age:"))
bp_input=float(input("BP:"))
al_input=float(input("AL:"))
su_input=float(input("SU:"))
bgr_input=float(input("BGR:"))
bu_input=float(input("BU:"))
sc_input=float(input("SC:"))
sod_input=float(input("SOD:"))
pot_input=float(input("POT:"))
hrmo_input=float(input("HRMO:"))
pcv_input=float(input("PCV:"))
wc_input=float(input("WC:"))
rc_input=float(input("RC:"))
sg_b_input=float(input("Sg B 0 OR 1:"))
sg_c_input=float(input("Sg C 0 OR 1:"))
sg_d_input=float(input("Sg D 0 OR 1:"))
sg_e_input=float(input("Sg E 0 OR 1:"))
rbc_normal_input=float(input("Rbc Normal 0 or 1:"))
pc_normal_input=float(input("Pc Normal 0 or 1:"))
pcc_present_input=float(input("Pcc Present 0 or 1:"))
ba_present_input=float(input("Ba Present 0 or 1:"))
htn_yes_input=float(input("Htn Yes 0 or 1:"))
dm_yes_input=float(input("Dm Yes 0 or 1:"))
cad_yes_input=float(input("Cad Yes 0 or 1:"))
appet_yes_input=float(input("Appet Yes 0 or 1:"))
pe_yes_input=float(input("Pe Yes 0 or 1:"))
ane_yes_input=float(input("Ane Yes 0 or 1:"))

Age: 78
BP: 99
AL: 34
SU: 56
BGR: 96
BU: 57
SC: 38
SOD: 34
POT: 45
HRMO: 67
PCV: 68
WC: 78
RC: 78
Sg B 0 OR 1: 1
Sg C 0 OR 1: 0
Sg D 0 OR 1: 1
Sg E 0 OR 1: 0
Rbc Normal 0 or 1: 1
Pc Normal 0 or 1: 0
Pcc Present 0 or 1: 1
Ba Present 0 or 1: 0
Htn Yes 0 or 1: 1
Dm Yes 0 or 1: 0
Cad Yes 0 or 1: 1
Appet Yes 0 or 1: 0
Pe Yes 0 or 1: 1
Ane Yes 0 or 1: 0

In [23]:
Future_Prediction=grid.predict([[age_input,bp_input,al_input,su_input,bgr_input,bu_input,sc_input,sod_input,pot_input,hrmo_input,pcv_input,wc_input,rc_input,sg_b_input,sg_c_input,sg_d_input,sg_e_input,rbc_normal_input,pc_normal_input,pcc_present_input,ba_present_input,htn_yes_input,dm_yes_input,cad_yes_input,appet_yes_input,pe_yes_input,ane_yes_input]])
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[1]

In [24]:
import pickle
filename="finalized_model_KNN_GridSearchCV.sav"
pickle.dump(grid,open(filename, 'wb'))

In [25]:
preinput=sc.transform([[78,99,34,56,96,57,38,34,45,67,68,78,78,1,0,1,0,1,0,1,0,1,0,1,0,1,0]])

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

In [26]:
preinput

array([[ 1.58937634e+00,  1.72232199e+00,  2.69263086e+01,
         5.61315240e+01, -7.02667697e-01, -5.93713265e-02,
         5.86048479e+00, -9.83470142e+00,  1.81656378e+01,
         2.01657244e+01,  3.56969723e+00, -3.43244045e+00,
         8.98304338e+01,  2.02864108e+00, -5.45491499e-01,
         2.21610269e+00, -1.38409133e-01,  3.89249472e-01,
        -1.95866374e+00,  2.91547595e+00, -2.35702260e-01,
         1.35269628e+00, -7.39264248e-01,  3.41565026e+00,
        -1.93649167e+00,  1.91485422e+00, -4.45194562e-01]])

In [27]:
loaded_model=pickle.load(open("finalized_model_KNN_GridSearchCV.sav", 'rb'))
result=loaded_model.predict(preinput)
result

array([1])

In [28]:
import numpy as np
def inverse_transform_dummies_with_if(array):
      result = np.array([0])

if np.array_equal(result, np.array([0])):
    print("No")
else:
    print("Yes")

Yes